<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SaaSPlatform.Application\SaaSPlatform.Application.csproj" />
		<ProjectReference Include="..\SaaSPlatform.Core.Billing\SaaSPlatform.Core.Billing.csproj" />
		<ProjectReference Include="..\SaaSPlatform.Core.Tenant\SaaSPlatform.Core.Tenant.csproj" />
		<ProjectReference Include="..\SaaSPlatform.Infrastructure\SaaSPlatform.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Models\Response\" />
		<Folder Include="Models\Requests\" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
