<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreKit.IAM\CoreKit.IAM.csproj" />
    <ProjectReference Include="..\CoreKit.Tenant\CoreKit.Tenant.csproj" />
    <ProjectReference Include="..\SaaSPlatform.SharedKernel\CoreKit.SharedKernel.csproj" />
  </ItemGroup>

</Project>
